---
# see https://github.com/nextapps-de/flexsearch#tokenizer-prefix-search for options
tokenizer: "full" # strict, forward, reverse, full
custom_domain: "" # "https://www.w3id.org/archlink/branches/" #"https://www.w3id.org/archlink/terms/" #"https://www.w3id.org/conservation/terms/" #"https://www.lassemempel.github.io/terminologies/" #  # "https://www.w3id.org/conservation/terms/" # "https://conservationdata.github.io/terms/" #"https://restaurierungs-und-konservierungsdaten.github.io/Metadaten/" # "https://lassemempel.github.io/LEIZA-Terminologien/" #"https://museumsvokabular-de.github.io/Museumsvokabular-Hub/" # "https://lassemempel.github.io/gatsbytest/"
fail_on_validation: true
searchableAttributes:
  - "prefLabel" # you should not delete this one
  - "notation"
  - "altLabel"
  - "hiddenLabel"
  - "example"
  - "definition"
  - "scopeNote"
ui:
  title: "Konservierungsthesaurus-Zweige in Dante" # "Restaurierungs- und Konservierungsdaten" # "Terminologien" # Title is mandatory
  logo: "Thesaurus_Logo.png" # "mv_logo.jpg" # "Thesaurus_Logo.png" # "Leiza_Logo_Deskriptor_CMYK_schwarz_LEIZA.jpg" # Path
  colors:
    skoHubWhite: "rgb(255, 255, 255)"
    skoHubDarkColor:  rgb(23, 35, 59) # rgb(34, 52, 102) # "rgb(15, 85, 75)" 
    skoHubMiddleColor: rgb(34, 52, 102) # "rgb(79, 98, 139)" # "rgb(20, 150, 140)" 
    skoHubLightColor: rgb(79, 98, 139) # "rgb(40, 200, 175)"
    skoHubThinColor: "rgb(55, 250, 210)"
    skoHubBlackColor: "rgb(5, 30, 30)"
    skoHubAction: rgb(232, 66, 72) #"rgb(230, 0, 125)"
    skoHubNotice:  rgb(250, 182, 0) # "rgb(250, 180, 50)"
    skoHubDarkGrey: "rgb(155, 155, 155)"
    skoHubMiddleGrey: "rgb(200, 200, 200)"
    skoHubLightGrey: "rgb(235, 235, 235)"
  fonts:
    regular:
      font_family: "Ubuntu"
      font_style: "normal"
      font_weight: 400
      name: "ubuntu-v20-latin-regular"
    bold:
      font_family: "Ubuntu"
      font_style: "normal"
      font_weight: 700
      name: "ubuntu-v20-latin-700"
