version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app # Links the source files to the running container
    network_mode: host # Shares container's network with host