name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    container: cypress/base:18.12.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo Using node version $(node --version)
      - run: echo Using npm version $(npm --version)
      - run: cypress/prepare-cypress-test.sh
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.5 # use the explicit version number
        with:
          start: npm run develop
          wait-on: http://localhost:3000/index.de.html
          config: baseUrl=http://localhost:3000