name: Docker

on:
  workflow_run:
    workflows: ["Build", "Jest Tests", "E2E Tests"]
    types:
      - completed

env:
  REGISTRY: 
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/233-tests' }} && ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: skohub/skohub-vocabs-docker
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            
      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test docker image
        run: |
          mkdir public
          mkdir data
          cp .env.example .env
          cp test/data/interactivityType.ttl data/
          docker run --rm -v $(pwd)/public:/app/public -v $(pwd)/data:/app/data -v $(pwd)/.env:/app/.env ${{ env.TEST_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
